/**
*@File keys.h
*Holds storage key definitions
*/

#pragma once

//----------PERSISTANT STORAGE KEYS---------
enum{
  PERSIST_KEY_MENU_FONT,
  PERSIST_KEY_TITLE_FONT,
  PERSIST_KEY_PAGE_FONT,
  PERSIST_KEY_BG_COLOR,
  PERSIST_KEY_TEXT_COLOR,
  PERSIST_KEY_BG_SELECTION_COLOR,
  PERSIST_KEY_TEXT_SELECTION_COLOR,
  PERSIST_KEY_ENABLE_PAGING    
};
